AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

# The aoc gem makes methods part_1 & part_2
Naming/VariableNumber:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 50
